<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.bxslider').bxSlider({
            adaptiveHeight: true,
            mode: 'fade',
            //captions: true,
            pager: false,
            auto: true,
            //autoControls: true
        });
    });
</script>

<ul class="bxslider">
    <li><img src="/skin/frontend/default/dietifrance/images/slider/group1/perfect-body-1.jpg" title="Equilibre Nutrionnel" /></li>
    <li><img src="/skin/frontend/default/dietifrance/images/slider/group1/perfect-body-2.jpg" title="Diététique Santé" /></li>
    <li><img src="/skin/frontend/default/dietifrance/images/slider/group1/perfect-body-3.jpg" title="Poids de forme" /></li>
</ul>