<?php echo $this->getChildHtml('custom_footer') ?>
<footer class="footer-container case">
    <div class="footer container">
        <div class="row">
            <div class="col-md-6 text-left">
                <section class="row-fluid">
                    <div class="copyright">
                        <address><?php echo $this->getCopyright() ?></address>          
                    </div>
                </section>
            </div>
            <div class="col-md-6 text-right">
                <section class="row-fluid">
                    <img src="/skin/frontend/default/dieti/images/paiement.png">
                </section>
            </div>
        </div>
    </div>
</footer>
