

<!-- jQuery library (served from Google) -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<!-- bxSlider Javascript file -->



<script src="//cdn.jsdelivr.net/bxslider/4.1.1/jquery.bxslider.js"></script>
<script src="//cdn.jsdelivr.net/bxslider/4.1.1/jquery.bxslider.min.js"></script>
<script src="//cdn.jsdelivr.net/bxslider/4.1.1/plugins/jquery.easing.1.3.js"></script>
<script src="//cdn.jsdelivr.net/bxslider/4.1.1/plugins/jquery.fitvids.js"></script>


<!-- bxSlider CSS file 
<link href="//cdn.jsdelivr.net/bxslider/4.1.1/jquery.bxslider.css" rel="stylesheet" />
-->

<ul class="bxslider">
<?php
		$a = $this->getItems();
	
	foreach($a as $items){
?>
	
	<li><a href="<?php echo $items->getUrl(); ?>" title="<?php echo $items->getTitre(); ?>"><img src="<?php echo $this->getSkinUrl("images/".$items->getImage()."") ?>" /></a></li>
	
	<?php 
	}

	?>
  	
</ul>


<script>
	$(document).ready(function(){
  $('.bxslider').bxSlider( { <?= $this->getConfig(); ?> } );
});
</script>