<div class="header-outer">
    <div class="header">
    	<div class="top">
	    	<div class="container">
	            <?php echo $this->getChildHtml('store_language') ?>
	            <p class="welcome-msg">
	            	<?php echo $this->getChildHtml('welcome') ?>
	            	<?php echo $this->getAdditionalHtml() ?>
	            </p>
			</div>
		</div>
		<div class="middle">
	    	<div class="container">
		    	<div class="logo">
		    	 	<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
			    	 	<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
			    	 </a>
			 	</div>
	            <?php echo $this->getChildHtml('topLinks') ?>
		        <?php echo $this->getChildHtml('topContainer'); ?>
		       	<?php echo $this->getChildHtml('cart'); ?>
			</div>
		</div>
	    <div class="bottom">
	    	<div class="container">
	    		<div class="search">
            		<?php echo $this->getChildHtml('topSearch') ?>
            	</div>
	    		<div class="menu">
	    			<?php echo $this->getChildHtml('topMenu') ?>
	    		</div>
        	</div>
        </div>
    </div>
</div>