<div class="container-fluid up-footer">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<ul>
					<span>Information</span>
					<li>
						<a href="">Qui sommes-nous ?</a>
					</li>
					<li>
						<a href="">Mentins légales</a>
					</li>
					<li>
						<a href="">CGV</a>
					</li>
				</ul>
			</div>
			<div class="col-md-2">
				<ul>
					<span>Mon Compte</span>
					<li>
						<a href="">Mon profil</a>
					</li>
					<li>
						<a href="">Mes commandes</a>
					</li>
				</ul>
			</div>
			<div class="col-md-2">
				<ul>
					<span>Infos</span>
					<li>
						<a href="">test</a>
					</li>
					<li>
						<a href="">test</a>
					</li>
				</ul>
			</div>
			<div class="col-md-2">
				<ul>
					<span>Suivez-nous</span>
					<li>
						<a href="">Facebook</a>
					</li>
					<li>
						<a href="">Twitter</a>
					</li>
				</ul>
			</div>
			<div class="col-md-3">
				<ul>
					<span>Contactez-nous</span>
					<li>
						<a href="">test</a>
					</li>
					<li>
						<a href="">test
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>