<div class="container-fluid plus">
	<div class="container">
		<div class="row">
			<div class="metas">
				<div class="meta meta-1">Paiement sécurisé</div>
				<div class="meta meta-2">Livraison Rapide</div>
				<div class="meta meta-3">100% Satisfait</div>
				<div class="meta meta-4">Site officiel Dietimeal</div>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid up-footer">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<ul>
					<span>Information</span>
					<li>
						<a href="">Qui sommes-nous ?</a>
					</li>
					<li>
						<a href="">Mentins légales</a>
					</li>
					<li>
						<a href="">CGV</a>
					</li>
				</ul>
			</div>
			<div class="col-md-2">
				<ul>
					<span>Mon Compte</span>
					<li>
						<a href="">Mon profil</a>
					</li>
					<li>
						<a href="">Mes commandes</a>
					</li>
				</ul>
			</div>
			<div class="col-md-2">
				<ul>
					<span>Infos</span>
					<li>
						<a href=""><img src="/skin/frontend/default/dieti/images/callout2.png"></a>
					</li>
					<li style="padding-top:10px;">
						<a href=""><img src="/skin/frontend/default/dieti/images/bibliographie.png"></a>
					</li>
				</ul>
			</div>
			<div class="col-md-2">
				<ul>
					<span>Suivez-nous</span>
					<li>
						<a href=""><i class="fa fa-facebook-square"></i> Facebook</a>
					</li>
					<li>
						<a href=""><i class="fa fa-twitter-square"></i> Twitter</a>
					</li>
				</ul>
			</div>
			<div class="col-md-3">
				<ul>
					<span>Contactez-nous</span>
					<li>
						<address>
							<strong>DIETIFRANCE</strong><br>
							2 Allée de Migelane, 33650<br>
							Saucats<br>
	  						<a href="mailto:contact@dietifrance.fr">contact@dietifrance.fr</a><br>
	  						<abbr title="Phone">Tél.</abbr> +33 (0)5 56 72 77 60<br>
	  						Contact par email
						</address>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>