<div class="container sub-content">
	<div class="row">
		<div class="col-md-4">
			<div class="row first">
				<img src="/skin/frontend/default/dieti/images/national-program.jpg" class="national-program">
			</div>
		</div>
		<div class="col-md-8">
			<div class="row last">
				<img src="/skin/frontend/default/dieti/images/what-your-body.jpg" class="what-your-body">
			</div>
		</div>
	</div>
</div>